#!/usr/bin/env python
import os
import six

from coverage.control import Coverage
from subunit.run import main


coverage = Coverage(source=["systemfixtures"], auto_data=True)
coverage.exclude("# pragma: no cover")

coverage.start()
main()
coverage.stop()
